spring.application.name=planifest
server.port=8085

#Configuración de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/planifestdb
spring.datasource.username=postgres
spring.datasource.password=123456789
spring.sql.init.platform=postgres

#JPA - Java Persistence api
spring.jpa.database=POSTGRESQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

#Thymelift vistas
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.mvc.view.prefix=/templates/
spring.mvc.view.suffix=.html

#Informacion para Correo masivo
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=aeda042b36da1b
spring.mail.password=b311cdab4d6b6a
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#API Mapa
google.maps.api.key=AIzaSyCgZPwudO2MG358I1CqrzctaVrIfclADcQ